
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { app, database } from '../firebaseConfig';
import {
  collection,
  addDoc,
  getDocs,
  doc,
  setDoc,
  updateDoc,
  deleteDoc
} from 'firebase/firestore';
import {
  getAuth
}from 'firebase/auth';
import { useRouter } from 'next/router';
export default function Home() {
  const [ID, setID] = useState(null);
  const [TeamName, setName] = useState('');
  const [MemberCount, setAge] = useState(null);
  //const [fireData, setFireData] = useState([]);
  const [isUpdate, setIsUpdate] = useState(false);
 
  const auth = getAuth();
  const user = auth.currentUser;


  const databaseRef = collection(database,user.email);
  let router = useRouter()
  useEffect(() => {
    let token = sessionStorage.getItem('Token')
    if (token) {
      getData()
    }
    if (!token) {
      router.push('/register')
    }
  }, [])


  const addData = () => {
    setDoc(doc(database,user.email,user.uid),{
      name: TeamName,
      age: Number(MemberCount)
    })
    //addDoc(databaseRef, {
     // name: TeamName,
     // age: Number(MemberCount)
    //})
      .then(() => {
        alert('Data Sent')
        getData()
        setName('')
        setAge(null)
        router.push('/q1')
      })
      .catch((err) => {
        console.error(err);
      })
  }
  const next = () => {
        router.push('/q1')}
        const next1 = () => {
          router.push('/q2')}

  const getData = async () => {
    await getDocs(databaseRef)
      .then((response) => {
        console.log(response.docs.map((data) => {
          return { ...data.data(), id: data.id }
        }))
      })
  }
  const logout = () => {
    sessionStorage.removeItem('Token')
    router.push('/login')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next CRUD AUTH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button onClick={logout}>Log Out</button>
        </div>
        <h1>Home</h1>

          <hr/>
          <button
          className={styles.button}
          onClick={next}
        >
          create team
        </button>
        {/* <hr/>
          <button
          className={styles.button}
          onClick={next}
        >
          view team
        </button>*/}
        <hr/>
          <button
          className={styles.button}
          onClick={next1}
        >
          join team
        </button> 
      </main>
    </div>
  )
}
