import styles from '../styles/Home.module.css'
import Head from 'next/head';
import { app } from '../firebaseConfig';
import { useEffect } from 'react';
import {
    getAuth,
    signInWithEmailAndPassword
} from 'firebase/auth'
import { useState } from 'react';
import { Router, useRouter } from 'next/router';
import { database } from '../firebaseConfig';
import {

    doc,
    getDoc,

  } from 'firebase/firestore';
  
export default function Register() {
    const auth = getAuth();
    const user = auth.currentUser;  

    const router = useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const signUp = async() => {
        const docRef = doc(database, 'T_head', user.email);
        const docRef1 = doc(database, 'members', user.email);
        const docSnap = await getDoc(docRef);
        const docSnap1 = await getDoc(docRef1);
        signInWithEmailAndPassword(auth, email, password)
            
        .then((response) => {
                console.log(response.user)
                sessionStorage.setItem('Token', response.user.accessToken);
                if (docSnap.exists()){
                    router.push('/v_h');
                }
                
                else{
                    if(docSnap1.exists()){
                        router.push('/v_m');
                    }
                    else{
                        router.push('/home');
                    }
                }
            })
            .catch(err => {
                alert('Cannot Log in')
            })
    }
    const register = () => {
        sessionStorage.removeItem('Token')
        router.push('/register')
      }

    useEffect(() => {
        let token = sessionStorage.getItem('Token')

        if(token){
            router.push('/login')
        }
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Next CRUD AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Login</h1>

                <input
                    placeholder='Email'
                    className={styles.inputBox}
                    onChange={(event) => setEmail(event.target.value)}
                    value={email}
                    type='email'
                />
                <input
                    placeholder='Password'
                    className={styles.inputBox}
                    onChange={(event) => setPassword(event.target.value)}
                    value={password}
                    type='password'
                />

                <button
                    className={styles.button}
                    onClick={signUp}
                >Sign In</button>
                <hr />
                <button
                    className={styles.button}
                    onClick={register}
                >register</button>
            </main>
        </div>
    )
}