import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import {
  collection,
  documentId,
  updateDoc,
  addDoc,
  doc,
  getDoc,
  getDocs,
  setDoc,
} from 'firebase/firestore';
import styles from '../styles/Home.module.css'
import { database } from '../firebaseConfig';
import { useRouter } from 'next/router';
import {
  getAuth
}from 'firebase/auth';
export default function Home() {
  const [tname, setteamname] = useState("");
  const [tcode, setcode] = useState("");
  const auth = getAuth();
  const router = useRouter();
  const user = auth.currentUser;
  //const databaseRef = 
  //const ;
 
    const addData = () => {
    setDoc(doc(database,'T_head',user.email),{
      name: tname,
      code: tcode
    })
    setDoc(doc(database,"Teams",tname),{
      A: user.email,
      idM:tcode
    })
     .then(() => {
      alert('Data Sent')
      router.push('/v_h')
    })
    .catch((err) => {
      console.error(err);
    })
}  

  return (
    <div className={styles.container}>
      <Head>
        <title>Next CRUD AUTH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          placeholder='team name'
          className={styles.inputBox}
          type="text"
          value={tname}
          onChange={event => setteamname(event.target.value)}
        />
     <input
          placeholder='team code'
          className={styles.inputBox}
          type="text"
          value={tcode}
          onChange={event => setcode(event.target.value)}
        />

        {(
          <button
            className={styles.button}
            onClick={addData}
          >
            Submit
          </button>
        )}
      </main>
    </div>
  )
}
